services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mosql
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  mongo:
    image: mongo:5
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/db-init.js:/docker-entrypoint-initdb.d/db-init.js
    networks:
      - db_network

volumes:
  postgres_data:
  mongo_data:

networks:
  db_network: